Class {
	#name : 'DragonLiteralConstructor',
	#superclass : 'DragonConstructor',
	#instVars : [
		'string'
	],
	#category : 'Dragon-Description',
	#package : 'Dragon',
	#tag : 'Description'
}

{ #category : 'converting' }
DragonLiteralConstructor >> constructorString [

	^ string
]

{ #category : 'accessing' }
DragonLiteralConstructor >> string [

	^ string
]

{ #category : 'accessing' }
DragonLiteralConstructor >> string: anObject [

	string := anObject
]
