Class {
	#name : 'OtCSerializationForScriptForLiteralTest',
	#superclass : 'OtCSerializationForScriptTest',
	#category : 'ObjectsToCode-Tests',
	#package : 'ObjectsToCode-Tests'
}

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptCharacter1 [

	^ '$a'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptCharacter2 [

	^ 'Character space'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptEmptyArray [

	^ '#()'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber1 [

	^ '1'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber2 [

	^ '789435132451674896432748797432132745644248679684354567897452312'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber3 [

	^ '-5'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber4 [

	^ '0'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber5 [

	^ '1.2315e-18'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber6 [

	^ '-1.2315e-18'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber7 [

	^ '2.849008609995305e106'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber8 [

	^ 'Float infinity'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptNumber9 [

	^ 'Float negativeInfinity'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptString1 [

	^ '''hello world'''
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForLiteralTest >> scriptString2 [

	^ ''''''
]
