Class {
	#name : 'OtCSerializationForScriptForPointTest',
	#superclass : 'OtCSerializationForScriptTest',
	#category : 'ObjectsToCode-Tests',
	#package : 'ObjectsToCode-Tests'
}

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForPointTest >> scriptPoint1 [

	^ '0 asPoint'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForPointTest >> scriptPoint2 [

	^ '0.5 asPoint'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForPointTest >> scriptPoint3 [

	^ '0 @ -0.5'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForPointTest >> scriptPoint4 [

	^ '0 @ 1'
]

{ #category : 'as yet unclassified' }
OtCSerializationForScriptForPointTest >> scriptPoint5 [

	^ '-0.232358 @ 1.12315'
]
