Trait {
	#name : 'PNEquipementTrainServices',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PassageNiveau-molecule',
	#package : 'PassageNiveau',
	#tag : 'molecule'
}

{ #category : 'nil' }
PNEquipementTrainServices >> autorisationDepart: unTrain [
]

{ #category : 'as yet unclassified' }
PNEquipementTrainServices >> interdictionDepart: unTrain [

	
]
