Trait {
	#name : 'PNSystemInformationGareServices',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PassageNiveau-molecule',
	#package : 'PassageNiveau',
	#tag : 'molecule'
}

{ #category : 'as yet unclassified' }
PNSystemInformationGareServices >> informTrainQuitteLaGare: unTrain [

	
]

{ #category : 'as yet unclassified' }
PNSystemInformationGareServices >> listeDesQuais [

	
]

{ #category : 'as yet unclassified' }
PNSystemInformationGareServices >> listeDesTrainsEnPartance [
]
