Trait {
	#name : 'PNSystemInformationGareEvents',
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : 'PassageNiveau-molecule',
	#package : 'PassageNiveau',
	#tag : 'molecule'
}

{ #category : 'as yet unclassified' }
PNSystemInformationGareEvents >> trainArriveEnGare: unTrain auQuai: unNombre [

	
]

{ #category : 'as yet unclassified' }
PNSystemInformationGareEvents >> trainEnPartence: unTrain auQuai: unNombre [

	
]

{ #category : 'as yet unclassified' }
PNSystemInformationGareEvents >> trainQuitteLaGare: unTrain auQuai: unNombre [

	
]
