Class {
	#name : 'CtPSAObject',
	#superclass : 'Object',
	#instVars : [
		'capellaObject',
		'name'
	],
	#category : 'CapellaToPharo',
	#package : 'CapellaToPharo'
}

{ #category : 'accessing' }
CtPSAObject >> capellaObject [

	^ capellaObject
]

{ #category : 'accessing' }
CtPSAObject >> capellaObject: anObject [

	capellaObject := anObject
]

{ #category : 'accessing' }
CtPSAObject >> name [

	^ name
]

{ #category : 'accessing' }
CtPSAObject >> name: anObject [

	name := anObject
]
