Class {
	#name : 'ProliExRailwayFacilities',
	#superclass : 'MolAbstractComponentImpl',
	#traits : 'ProliExRailwayFacilitiesType + ProliExControlPowerSupplyToTrainsService',
	#classTraits : 'ProliExRailwayFacilitiesType classTrait + ProliExControlPowerSupplyToTrainsService classTrait',
	#category : 'PrototypeLink-Example-implementations',
	#package : 'PrototypeLink-Example',
	#tag : 'implementations'
}
