Class {
	#name : 'DragonSerializationForScriptForLiteralTest',
	#superclass : 'DragonSerializationForScriptTest',
	#category : 'Dragon-Tests',
	#package : 'Dragon-Tests'
}

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptCharacter1 [

	^ '$a'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptCharacter2 [

	^ 'Character space'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptEmptyArray [

	^ '#()'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber1 [

	^ '1'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber2 [

	^ '789435132451674896432748797432132745644248679684354567897452312'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber3 [

	^ '-5'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber4 [

	^ '0'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber5 [

	^ '1.2315e-18'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber6 [

	^ '-1.2315e-18'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber7 [

	^ '2.849008609995305e106'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber8 [

	^ 'Float infinity'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptNumber9 [

	^ 'Float negativeInfinity'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptString1 [

	^ '''hello world'''
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForLiteralTest >> scriptString2 [

	^ ''''''
]
