Class {
	#name : 'DragonSerializationForScriptForPointTest',
	#superclass : 'DragonSerializationForScriptTest',
	#category : 'Dragon-Tests',
	#package : 'Dragon-Tests'
}

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForPointTest >> scriptPoint1 [

	^ '0 asPoint'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForPointTest >> scriptPoint2 [

	^ '0.5 asPoint'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForPointTest >> scriptPoint3 [

	^ '0 @ -0.5'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForPointTest >> scriptPoint4 [

	^ '0 @ 1'
]

{ #category : 'as yet unclassified' }
DragonSerializationForScriptForPointTest >> scriptPoint5 [

	^ '-0.232358 @ 1.12315'
]
